name: logikal-middleware
services:
- name: logikal-middleware
  github:
    repo: scrollit/logikal-middleware
    branch: main
  run_command: python startup.py
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  dockerfile_path: Dockerfile
  envs:
  - key: ENVIRONMENT
    value: production
  - key: DEBUG
    value: "false"
  # NOTE: SECRET environment variables (SECRET_KEY, JWT_SECRET_KEY, REDIS_URL, 
  # LOGIKAL_AUTH_USERNAME, LOGIKAL_AUTH_PASSWORD, ADMIN_USERNAME, ADMIN_PASSWORD)
  # are managed via DigitalOcean Console and should NOT be specified here.
  # They are configured as encrypted secrets in the DigitalOcean App Platform settings.
  - key: DATABASE_URL
    value: ${logikal-db.DATABASE_URL}
  - key: LOGIKAL_API_BASE_URL
    value: "http://128.199.57.77/MbioeService.svc/api/v3/"
  - key: ADMIN_SESSION_EXPIRE_HOURS
    value: "8"
  - key: LOG_LEVEL
    value: "INFO"
  - key: LOG_FORMAT
    value: "json"
  - key: PROMETHEUS_ENABLED
    value: "true"
  - key: RATE_LIMIT_PER_MINUTE
    value: "1000"
  - key: RATE_LIMIT_PER_HOUR
    value: "10000"
  - key: BACKGROUND_SYNC_ENABLED
    value: "false"
  - key: SYNC_INTERVAL_SECONDS
    value: "300"
  - key: WORKERS
    value: "1"
  health_check:
    http_path: /api/v1/health

databases:
- name: logikal-db
  engine: PG
  version: "15"
  size: db-s-dev-database
  num_nodes: 1

# Optional: Redis for Celery (if needed)
# databases:
# - name: logikal-redis
#   engine: REDIS
#   version: "7"
#   size: db-s-dev-database
#   num_nodes: 1
