"""add_status_to_elevations

Revision ID: 00d43e14de15
Revises: 5b273678e0c3
Create Date: 2025-09-29 20:51:40.317407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d43e14de15'
down_revision: Union[str, Sequence[str], None] = '5b273678e0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elevations', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elevations', 'status')
    # ### end Alembic commands ###
