"""fix_phase_id_type

Revision ID: 3a931d95f15a
Revises: 00d43e14de15
Create Date: 2025-09-29 20:53:10.611199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a931d95f15a'
down_revision: Union[str, Sequence[str], None] = '00d43e14de15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE elevations ALTER COLUMN phase_id TYPE INTEGER USING phase_id::integer')
    op.create_foreign_key(None, 'elevations', 'phases', ['phase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'elevations', type_='foreignkey')
    op.alter_column('elevations', 'phase_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
