"""Add directory exclusion and sync fields

Revision ID: b225f7ccabee
Revises: 0c57a93ac64f
Create Date: 2025-09-23 18:39:19.155884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b225f7ccabee'
down_revision: Union[str, Sequence[str], None] = '0c57a93ac64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directories', sa.Column('full_path', sa.String(length=500), nullable=True))
    op.add_column('directories', sa.Column('level', sa.Integer(), nullable=True))
    
    # Add exclude_from_sync column as nullable first, then update existing records, then make it NOT NULL
    op.add_column('directories', sa.Column('exclude_from_sync', sa.Boolean(), nullable=True))
    op.execute("UPDATE directories SET exclude_from_sync = FALSE WHERE exclude_from_sync IS NULL")
    op.alter_column('directories', 'exclude_from_sync', nullable=False)
    
    op.add_column('directories', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('directories', sa.Column('last_api_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('directories', sa.Column('api_created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('directories', sa.Column('api_changed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('directories', sa.Column('sync_status', sa.String(length=50), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE directories SET level = 0 WHERE level IS NULL")
    op.execute("UPDATE directories SET sync_status = 'pending' WHERE sync_status IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directories', 'sync_status')
    op.drop_column('directories', 'api_changed_date')
    op.drop_column('directories', 'api_created_date')
    op.drop_column('directories', 'last_api_sync')
    op.drop_column('directories', 'synced_at')
    op.drop_column('directories', 'exclude_from_sync')
    op.drop_column('directories', 'level')
    op.drop_column('directories', 'full_path')
    # ### end Alembic commands ###
