"""add_sync_fields_to_phases_elevations

Revision ID: d4e5f6a7b8c9
Revises: 693e88501a64
Create Date: 2025-01-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, Sequence[str], None] = '693e88501a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phases', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('phases', sa.Column('sync_status', sa.String(length=50), nullable=True, default='pending'))
    op.add_column('elevations', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('elevations', sa.Column('sync_status', sa.String(length=50), nullable=True, default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elevations', 'sync_status')
    op.drop_column('elevations', 'synced_at')
    op.drop_column('phases', 'sync_status')
    op.drop_column('phases', 'synced_at')
    # ### end Alembic commands ###
